apiVersion: apps/v1
kind: Deployment
metadata:
  name: etudiant-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etudiant-api
  template:
    metadata:
      labels:
        app: etudiant-api
    spec:
      containers:
      - name: etudiant-api
        image: <votre-username>/etudiant-service:1.0
        imagePullPolicy: Always
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres-service:5432/etudiants
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          value: 1234
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: etudiant-api-service
spec:
  selector:
    app: etudiant-api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
