spring.application.name=etudiants-api
# Port de l'application
server.port=8085
# Configuration de la base de donnees PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/etudiants
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
